config/routes.rb
Rails.application.routes.draw do

  root 'classifieds#index'

  resources :classifieds

  get 'authenticate/register' => 'authenticate#register'
  post 'authenticate/create_user' => 'authenticate#create_user'
  post 'authenticate/login' => 'authenticate#login'
  get 'authenticate/logout' => 'authenticate#logout'

end

app/models/authenticate.rb
class Authenticate < ActiveRecord::Base

end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
def register
  end

  def create_user
    u = User.new
    u.fname = params[:first_name]
    u.lname = params[:last_name]
    u.email = params[:email]
    u.password = params[:password]

    if  u.save!
      flash[:notice] = "User created Successfully"
      session[:user_id] =  u.id
      redirect_to root_url
    else
      render :register
    end

  end

  def login
    @user = User.where(:email => params[:email]).first
    if !@user.nil? && @user.password == params[:password]
      session[:user_id]  = @user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to root_url
     else
      flash[:notice] = "unable to login"
      render :register
     end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :set_classified, only: [:show, :edit, :update, :destroy]

  # GET /classifieds
  # GET /classifieds.json
  def index
    @classifieds = Classified.all
  end

  # GET /classifieds/1
  # GET /classifieds/1.json
  def show
  end

  # GET /classifieds/new
  def new
    @classified = Classified.new
  end

  # GET /classifieds/1/edit
  def edit
  end

  # POST /classifieds
  # POST /classifieds.json
  def create
    @classified = Classified.new(classified_params)

    respond_to do |format|
      if @classified.save
        format.html { redirect_to @classified, notice: 'Classified was successfully created.' }
        format.json { render :show, status: :created, location: @classified }
      else
        format.html { render :new }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifieds/1
  # PATCH/PUT /classifieds/1.json
  def update
    respond_to do |format|
      if @classified.update(classified_params)
        format.html { redirect_to @classified, notice: 'Classified was successfully updated.' }
        format.json { render :show, status: :ok, location: @classified }
      else
        format.html { render :edit }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifieds/1
  # DELETE /classifieds/1.json
  def destroy
    @classified.destroy
    respond_to do |format|
      format.html { redirect_to classifieds_url, notice: 'Classified was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classified
      @classified = Classified.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classified_params
      params.require(:classified).permit(:category, :title, :description, :keyword, :address1, :address2, :city, :state, :zip, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/views/authenticate/register.html.erb
                        <hr class="topbar"/>
            <div class="container">
    <br />
    <div class="row">

        <div class="col-sm-12">
            <h1>Create an account</h1>

            <hr />
            <div class="row">
                <div class="col-sm-12 col-md-6">



                    <%=form_tag "create_user", :class=>"form-vertical" do %>
                        <fieldset>

                            <div class="row">
                                <div class="col-sm-12" >

                                    <div class="well">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Full name</label>
                                            <div class="row">
                                                <div class="col-sm-3">
                                                    <select class="form-control">
                                                        <option value="1">Mr</option>
                                                        <option value="2">Mrs</option>
                                                        <option value="3">Miss</option>
                                                        <option value="4">Ms</option>
                                                        <option value="5">Dr</option>
                                                    </select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <input type="text" name="first_name" class="form-control " id="exampleInputEmail1" placeholder="First name">
                                                </div>

                                              <div class="col-sm-5">
                                                    <input type="text" class="form-control " id="exampleInputEmail1" name="last_name" placeholder="Last name">
                                                </div>
                                            </div>

                                        </div>


                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email address</label>
                                            <input type="email" class="form-control " id="exampleInputEmail1" placeholder="Enter email" name="email">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Password</label>
                                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Make sure your password is longer than 6 characters" name="password">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Confirm password</label>
                                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm your password" name="c_password">
                                        </div>

                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> We can contact you with relevant properties, offers and news
                                            </label>
                                        </div>
                                        <br />
                                       <button type="submit" class="btn btn-primary" > Create User</button>



                                    </div>
                                </div>




                            </div>

                        </div>

                        <div class="col-md-6 col-sm-12 account-sidebar hidden-sm">

                            <div class="row">
                                <div class="col-sm-3" style="text-align: center;">
                                    <img src="css/images/icons/Crest.png" width="50"/>
                                </div>
                                <div class="col-sm-8">
                                    <h3>Why us?</h3>
                                    <p>We're one of the most recognisable brands, attracting thousands of buyers every month.<p>
                                    </div>
                            </div>
                            <br />

                            <div class="row">
                                <div class="col-sm-3" style="text-align: center;">
                                    <img src="css/images/icons/Pie-Chart.png" width="40"/>
                                </div>
                                <div class="col-sm-8">
                                    <h3>Magnet for buyers</h3>
                                    <p>We make sure your listings receive maximum exposure and is presented in an engaging way</p>
                                </div>
                            </div>
                            <br />

                            <div class="row">
                                <div class="col-sm-3" style="text-align: center;">
                                    <img src="css/images/icons/Search.png" width="40"/>
                                </div>
                                <div class="col-sm-8">
                                    <h3>Focused searches</h3>
                                    <p>Our technology and algorithm matches potential buyers directly to your listings</p>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-sm-3" style="text-align: center;">
                                    <img src="css/images/icons/Telephone.png" width="40"/>
                                </div>
                                <div class="col-sm-8">
                                    <h3>Mobile web</h3>
                                    <p>Your listings will always be accessible to everyone, even when they are on the move, via our responsive mobile website</p>
                                </div>
                            </div>

                        </div>

                    </div>
                    <br />






                </fieldset>
<% end %>
        </div>
    </div>
</div>




</div>
</div>


<!-- Modal -->
<div class="modal fade" id="modalForgot" tabindex="-1" role="dialog" aria-labelledby="modalForgot" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Forgot your password?</h4>
            </div>
            <div class="modal-body">
                <p>Enter your email to continue</p>

                <form role="form">
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Your email address">
                    </div>

                    <div class="row">
                        <div class="col-md-6">

                        </div><div class="col-md-6">
                        <a href="my_account.html" class="btn btn-primary pull-right">Continue</a>
                        </div>
                    </div>
                </form>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="footer">
    <div class="container">

        <div class="row">

            <div class="col-sm-4 col-xs-12">
                <p><strong>&copy; Bootstrap Classifieds 2014</strong></p>
                <p>All rights reserved</p>
            </div>

            <div class="col-sm-8 col-xs-12">
                <p class="footer-links">
                    <a href="index.html" class="active">Home</a>
                    <a href="typography.html">Typography</a>
                    <a href="terms.html">Terms and Conditions</a>
                    <a href="contact.html">Contact Us</a>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/classifieds/_form.html.erb
<hr class="topbar"/>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="sidebar-account">		
	<div class="row ">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">My account</div>
				<div class="panel-body">
					<ul class="nav">
						<li>
							<a class="active" href="account_dashboard.html">Dashboard</a>
						</li>						
						<li>	
							<a class="active" href="account_profile.html">My profile</a>
						</li>
                        <li>
							<a class="active" href="account_account.html">My account</a>
						</li>
						<li>
							<a class="active" href="account_ads.html">Manage ads</a>
						</li>
						<li>
							<a class="active" href="account_ad_create.html">Create new ad</a>
						</li>
					</ul>

				</div>
			</div>
		</div>
	</div>

	<div class="row hidden-xs">
<div class="col-lg-12">
		<div class="well">
			<div class="row ">
<div class="col-lg-3">
												<img src="/assets/icons/Crest.png" width="45"/>
											</div>
			<div class="col-lg-9">

<h4 style="margin-top: 0">Increase visibility</h4>
			<p>Don't forget to 'bump' your listing to gain more visibility</p>

			</div>
			</div>

		</div>
		</div>
		</div>

</div>
        </div>

        <div class="col-sm-9">
            <%= form_for(@classified, :html =>{class: "form-vertical"} ) do |f| %>  
                <% if @classified.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@classified.errors.count, "error") %> prohibited this classified from being saved:</h2>

                      <ul>
                      <% @classified.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                <div class="panel panel-default">
                    <div class="panel-heading">Choose category</div>
                    <div class="panel-body">


                        <div class="row">  
                            <div class="col-sm-12 "  >

                                <div class="form-group">

                                    <div class="row">
                                        <div class="col-sm-2" style="margin-top: 10px;">
                                            <label>Category</label>

                                        </div>
                                        <div class="col-sm-6">
                                           <% @vehicles = ["Cars","Motorcycles", "Boats","Other"]%>
                                           <% @real_estate = ["Home for Rent","Home for Sale","Other"]%>
                                          <% @services = ["Auto", "Food", "Computer Services"]%>
                                           <% @categories_array = [["vehicles", @vehicles], ["Real Estate", @real_estate], ["Services", @services]]%>
                                          
                                           <%= f.select :category,grouped_options_for_select(@categories_array), id: "category", class: "form-control"%>
                                            
                                        </div>

                                    </div>
                                </div>			
                            </div>			
                        </div>			
                    </div>			
                </div>


                <div class="panel panel-default">
                    <div class="panel-heading">Ad details</div>
                    <div class="panel-body">




                        <div class="form-group">
                            <div class="row">

                                <div class="col-sm-12">
                                    <label>Title </label>
                                    <%= f.text_field :title, :class => "form-control" %>
                                </div>
                                <div class="col-sm-12"><br />
                                    <label>Description </label>
                                  <%= f.text_area :description, :class => "form-control col-sm-8 expand", :rows => "6", :style => "width: 99%" %>
                    
                                </div>

                                <div class="col-sm-12"><br />
                                    <label>Keywords</label>
                                    <%= f.text_field :keyword, :class => "form-control"%>
                                </div>		

                            </div>

                        </div>




                    </div>			
                </div>			

                <div class="panel panel-default">
                    <div class="panel-heading">Ad information</div>
                    <div class="panel-body">

                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label>Address1</label>
                                    <%= f.text_field :address1, :class => "form-control"%>
                                </div>									     	
                                <div class="col-sm-6">
                                    <label>Address2</label>
                                    <%= f.text_field :address2, :class => "form-control"%>
                                </div>
                                <div class="col-sm-6"><br />
                                    <label>City</label>
                                    <%= f.text_field :city, :class => "form-control"%>
                                </div>
                                <div class="col-sm-6"><br />
                                    <label>Post Code</label>
                                    <%= f.text_field :zip, :class => "form-control"%>
                                </div>


                            </div>
                            <br />
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="optionsRadios" id="optionsRadios2" value="option2">
                                            Don't show my address details publicly
                                        </label>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>


                <div class="panel panel-default">
                    <div class="panel-heading">Add photos</div>
                    <div class="panel-body">
                        <div id="my-dropzone" action="upload.php" class="dropzone"></div>
                        <br /><p><small>* please note that the displayed images are cropped/resized only for display purposes</small></p>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Your price</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <input type="text" class="form-control "  placeholder="How much do you want it to be listed for?">
                                </div>
                                <div class="col-sm-6">
                                    <p>You can adjust your price anytime you like, even after your listing is published.</p>
                                </div>
                            </div>
                        </div>

                    </div>




                </div>	

                <div class="panel panel-default">
                    <div class="panel-heading">Complete ad</div>
                    <div class="panel-body">

                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> I agree to the terms and conditions and regulations.
                            </label>
                        </div>

                        <br />
                        <button type="submit" class="btn btn-default hidden-xs">Save draft</button>
                        <button type="submit" class="btn btn-default hidden-xs">Preview ad</button>
                        <a href="account_credits.html" class="btn btn-primary pull-right"><i class="icon-ok"></i>  Publish ad</a>
                        <br /><p class=" hidden-xs" style="text-align: right"><small>* payment options will be<br /> shown on the next screen</small></p>
                    </div>
                    <% end %>



                </div>

            </div>




        </div>
    </div>
</div>

<br />

</div>
</div><!-- Modal -->
<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modalLogin" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Sign in to your account</h4>
            </div>
            <div class="modal-body">
                <p>If you have an account with us, please enter your details below.</p>

                <form method="POST" action="account_dashboard.html" accept-charset="UTF-8" id="user-login-form" class="form ajax" data-replace=".error-message p">

                    <div class="form-group">
                        <input placeholder="Your username/email" class="form-control" name="email" type="text">                </div>

                    <div class="form-group">
                        <input placeholder="Your password" class="form-control" name="password" type="password" value="">                </div>

                    <div class="row">
                        <div class="col-md-6">

                        </div>
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary pull-right">Login</button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <a data-toggle="modal" href="#modalForgot">Forgot your password?</a>
                        </div>
                    </div>

                </form>
            </div>

            <div class="modal-footer" style="text-align: center">
                <div class="error-message"><p style="color: #000; font-weight: normal;">Don't have an account? <a class="link-info" href="register.html">Register now</a></p></div>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="modalForgot" tabindex="-1" role="dialog" aria-labelledby="modalForgot" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Forgot your password?</h4>
            </div>
            <div class="modal-body">
                <p>Enter your email to continue</p>

                <form role="form">
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Your email address">
                    </div>

                    <div class="row">
                        <div class="col-md-6">

                        </div><div class="col-md-6">
                        <a href="my_account.html" class="btn btn-primary pull-right">Continue</a>
                        </div>
                    </div>
                </form>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="footer">
    <div class="container">

        <div class="row">

            <div class="col-sm-4 col-xs-12">
                <p><strong>&copy; Bootstrap Classifieds 2014</strong></p>
                <p>All rights reserved</p>
            </div>			

            <div class="col-sm-8 col-xs-12">
                <p class="footer-links">
                    <a href="index.html" class="active">Home</a>
                    <a href="typography.html">Typography</a>
                    <a href="terms.html">Terms and Conditions</a>
                    <a href="contact.html">Contact Us</a>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/classifieds/edit.html.erb
<h1>Editing Classified</h1>

<%= render 'form' %>

<%= link_to 'Show', @classified %> |
<%= link_to 'Back', classifieds_path %>

app/views/classifieds/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', classifieds_path %>

app/views/classifieds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @classified.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @classified.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @classified.description %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @classified.keyword %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @classified.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @classified.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @classified.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @classified.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @classified.zip %>
</p>

<p>
  <strong>Price:</strong>
  <%= @classified.price %>
</p>

<%= link_to 'Edit', edit_classified_path(@classified) %> |
<%= link_to 'Back', classifieds_path %>